version: '3.8'

services:

  # ===========================
  # FRONTEND
  # ===========================
  frontend:
    build: ./frontend
    container_name: fe
    networks:
      - mon_net

  # ===========================
  # BACKEND
  # ===========================
  backend:
    build: ./backend
    container_name: be
    networks:
      - mon_net

  # ===========================
  # NGINX PROXY
  # ===========================
  nginx:
    build: ./nginx
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - mon_net
    volumes:
      - ./nginx/logs:/var/log/nginx

  # ===========================
  # NODE EXPORTER (CPU SERVER)
  # ===========================
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/host'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro
    networks:
      - mon_net
    pid: host
    restart: unless-stopped

  # ===========================
  # CADVISOR (CPU DOCKER)
  # ===========================
  cadvisor:
    image: zcube/cadvisor:latest  
    container_name: cadvisor
    ports:
      - "8081:8080"
    networks:
      - mon_net
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    privileged: true
    restart: unless-stopped

  # ===========================
  # NGINX EXPORTER (Traffic)
  # ===========================
  nginx_exporter:
    image: nginx/nginx-prometheus-exporter:latest
    container_name: nginx_exporter
    command: ["-nginx.scrape-uri", "http://nginx/nginx_status"]
    ports:
      - "9113:9113"
    networks:
      - mon_net
    depends_on:
      - nginx
    restart: unless-stopped

  # ===========================
  # PROMETHEUS
  # ===========================
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/alert.rules:/etc/prometheus/alert.rules
    networks:
      - mon_net
    restart: unless-stopped

  # ===========================
  # ALERT MANAGER
  # ===========================
  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - mon_net
    restart: unless-stopped
  # ===========================
  # GO ACCESS
  # ===========================
  goaccess:
    image: allinurl/goaccess:latest
    container_name: goaccess
    depends_on:
      - nginx
    networks:
      - mon_net
    ports:
      - "7890:7890"
    volumes:
      - ./nginx/logs:/logs:ro
      - ./goaccess:/report
    restart: unless-stopped
    entrypoint: ["goaccess"]
    command:
      - /logs/access.log
      - --log-format=%h %^ %e [%d:%t %^] "%r" %s %b "%R" "%u"
      - --date-format=%d/%b/%Y
      - --time-format=%T
      - --real-time-html
      - --ws-url=ws://192.168.186.146:7890
      - --port=7890
      - -o
      - /report/report.html

  goaccess_web:
    image: nginx:alpine
    container_name: goaccess_web
    ports:
      - "7880:80"
    volumes:
      - ./goaccess:/usr/share/nginx/html:ro
    networks:
      - mon_net
    restart: unless-stopped







networks:
  mon_net:
    driver: bridge
