global:
  resolve_timeout: 1m

route:
  receiver: telegram_channel

receivers:
  - name: telegram_channel
    telegram_configs:
      - bot_token: "8133242338:AAFMStN4OmT8-j3P_UxVepLvVf9x5pqToCk"
        chat_id: 6163552209
        parse_mode: "Markdown"
        message: |
          ðŸš¨ *DDoS ALERT DETECTED*
          *Description:* {{ .CommonAnnotations.description }}
          *Alert:* {{ .CommonLabels.alertname }}
          *Severity:* {{ .CommonLabels.severity }}
          *Status:* {{ .Status }}
          *Time:* {{ .StartsAt }}
